import type { DiscoveryAd } from "@/types/inspo"

// Mock data — replace with real API/DB when available
// Images use picsum.photos with stable seeds for consistency
export const MOCK_ADS: DiscoveryAd[] = [
  {
    id: "ad_001",
    brandName: "Rosabella Beetroot",
    brandAvatar: "https://picsum.photos/seed/rosabella/40/40",
    headline: "Introducing Rosabella Organic Beetroot",
    primaryText: "Wellness fits into busy schedules. 1300mg per serving — supports health & circulation. 30-day supply.",
    mediaUrl: "https://picsum.photos/seed/beetroot/640/640",
    mediaType: "image",
    cta: "Learn more",
    platform: "facebook",
    format: "image",
    category: "Health & Wellness",
    language: "English",
    views: 258900,
    estimatedSpend: 3900,
    runningDays: 43,
    firstSeenAt: "2026-03-20",
    angle: "Social Proof",
    emotion: "Trust",
    theme: "Minimalist",
    usp: "Organic",
    desire: "Health",
    tags: ["supplement", "health", "organic"],
  },
  {
    id: "ad_002",
    brandName: "QREAM Jewelry",
    brandAvatar: "https://picsum.photos/seed/qream/40/40",
    headline: "Premium Men's Jewelry – Built to Last",
    primaryText: "The chain that sold out 3 times is now back in stock. Reserve now before it sells out.",
    mediaUrl: "https://picsum.photos/seed/jewelry/640/640",
    mediaType: "video",
    duration: "00:08",
    cta: "Shop now",
    platform: "instagram",
    format: "video",
    category: "Jewelry & Accessories",
    language: "English",
    views: 1100000,
    estimatedSpend: 17200,
    runningDays: 206,
    firstSeenAt: "2025-07-15",
    angle: "Urgency / Scarcity",
    emotion: "Desire",
    theme: "Premium",
    usp: "Limited Stock",
    desire: "Status",
    tags: ["jewelry", "men", "luxury"],
  },
  {
    id: "ad_003",
    brandName: "Sasha Therese",
    brandAvatar: "https://picsum.photos/seed/sasha/40/40",
    headline: "The dress you can tie 5 ways",
    primaryText: "Shop new arrivals. Versatile, stylish, and perfect for any occasion.",
    mediaUrl: "https://picsum.photos/seed/dress/640/640",
    mediaType: "video",
    duration: "00:06",
    cta: "Shop now",
    platform: "instagram",
    format: "video",
    category: "Fashion",
    language: "English",
    views: 175000,
    estimatedSpend: 2600,
    runningDays: 16,
    firstSeenAt: "2026-04-27",
    angle: "Problem / Solution",
    emotion: "Joy",
    theme: "Lifestyle",
    usp: "Versatile",
    desire: "Beauty",
    tags: ["fashion", "dress", "women"],
  },
  {
    id: "ad_004",
    brandName: "The Health Haven",
    brandAvatar: "https://picsum.photos/seed/healthhaven/40/40",
    headline: "If your energy is gone by noon, take...",
    primaryText: "Support stamina and heart health. Best customer support ever. My energy is back!",
    mediaUrl: "https://picsum.photos/seed/energy/640/640",
    mediaType: "image",
    cta: "Learn more",
    platform: "facebook",
    format: "image",
    category: "Health & Wellness",
    language: "English",
    views: 131100,
    estimatedSpend: 2000,
    runningDays: 14,
    firstSeenAt: "2026-04-29",
    angle: "Curiosity",
    emotion: "Fear",
    theme: "Bold",
    usp: "Natural Ingredients",
    desire: "Health",
    tags: ["supplement", "energy", "health"],
  },
  {
    id: "ad_005",
    brandName: "HelloIce",
    brandAvatar: "https://picsum.photos/seed/helloice/40/40",
    headline: "Helloice Purple Diamonds Hoop Earrings",
    primaryText: "Premium jewelry at accessible prices. Handcrafted with love.",
    mediaUrl: "https://picsum.photos/seed/earrings/640/640",
    mediaType: "image",
    cta: "Shop now",
    platform: "instagram",
    format: "image",
    category: "Jewelry & Accessories",
    language: "English",
    views: 93000,
    estimatedSpend: 1400,
    runningDays: 287,
    firstSeenAt: "2025-07-30",
    angle: "Social Proof",
    emotion: "Desire",
    theme: "Premium",
    usp: "Handcrafted",
    desire: "Status",
    tags: ["jewelry", "earrings", "women"],
  },
  {
    id: "ad_006",
    brandName: "TubsJackson",
    brandAvatar: "https://picsum.photos/seed/tubsjackson/40/40",
    headline: "Join over 3,000+ riders who've made the switch",
    primaryText: "The smoothest ride you'll ever experience. Built for performance.",
    mediaUrl: "https://picsum.photos/seed/cycling/640/640",
    mediaType: "image",
    cta: "Learn more",
    platform: "facebook",
    format: "image",
    category: "Sports & Fitness",
    language: "English",
    views: 44200,
    estimatedSpend: 662,
    runningDays: 84,
    firstSeenAt: "2025-09-20",
    angle: "Social Proof",
    emotion: "Excitement",
    theme: "Bold",
    usp: "Community",
    desire: "Achievement",
    tags: ["cycling", "sports", "fitness"],
  },
  {
    id: "ad_007",
    brandName: "Taraiga",
    brandAvatar: "https://picsum.photos/seed/taraiga/40/40",
    headline: "All Items are Up to 70% Off + 10% Off",
    primaryText: "Limited time sale. Shop now and save big on all items.",
    mediaUrl: "https://picsum.photos/seed/sale/640/640",
    mediaType: "image",
    cta: "Shop now",
    platform: "facebook",
    format: "image",
    category: "Fashion",
    language: "English",
    views: 55800,
    estimatedSpend: 836,
    runningDays: 17,
    firstSeenAt: "2026-01-26",
    angle: "Discount / Offer",
    emotion: "Excitement",
    theme: "Sale",
    usp: "Discount",
    desire: "Savings",
    tags: ["fashion", "sale", "discount"],
  },
  {
    id: "ad_008",
    brandName: "Virtuzone",
    brandAvatar: "https://picsum.photos/seed/virtuzone/40/40",
    headline: "Start your Dubai business with 100%...",
    primaryText: "Setup your company in Dubai with 100% foreign ownership. Fast, reliable, trusted.",
    mediaUrl: "https://picsum.photos/seed/dubai/640/640",
    mediaType: "image",
    cta: "Get started",
    platform: "facebook",
    format: "image",
    category: "Business & Finance",
    language: "English",
    views: 22600,
    estimatedSpend: 338,
    runningDays: 51,
    firstSeenAt: "2025-11-23",
    angle: "Authority",
    emotion: "Trust",
    theme: "Corporate",
    usp: "100% Foreign Ownership",
    desire: "Success",
    tags: ["business", "dubai", "b2b"],
  },
  {
    id: "ad_009",
    brandName: "GlowSkin Co",
    brandAvatar: "https://picsum.photos/seed/glowskin/40/40",
    headline: "Why dermatologists love this serum",
    primaryText: "Finally, a serum that actually works. 94% of users saw results in 2 weeks. Fragrance-free, dermatologist tested.",
    mediaUrl: "https://picsum.photos/seed/serum/640/640",
    mediaType: "video",
    duration: "00:15",
    cta: "Shop now",
    platform: "instagram",
    format: "video",
    category: "Beauty & Skincare",
    language: "English",
    views: 2300000,
    estimatedSpend: 45000,
    runningDays: 120,
    firstSeenAt: "2025-10-15",
    angle: "Authority",
    emotion: "Trust",
    theme: "Clean / Minimal",
    usp: "Dermatologist Tested",
    desire: "Beauty",
    tags: ["skincare", "serum", "beauty"],
  },
  {
    id: "ad_010",
    brandName: "FitMeal Prep",
    brandAvatar: "https://picsum.photos/seed/fitmeal/40/40",
    headline: "Lose 10 lbs without counting calories",
    primaryText: "Our meal prep delivery service does all the work. Healthy, delicious, macro-balanced meals delivered to your door.",
    mediaUrl: "https://picsum.photos/seed/mealprep/640/640",
    mediaType: "video",
    duration: "00:30",
    cta: "Get offer",
    platform: "facebook",
    format: "video",
    category: "Food & Nutrition",
    language: "English",
    views: 890000,
    estimatedSpend: 12000,
    runningDays: 90,
    firstSeenAt: "2025-12-01",
    angle: "Transformation",
    emotion: "Hope",
    theme: "Lifestyle",
    usp: "Convenient",
    desire: "Health",
    tags: ["food", "diet", "fitness"],
  },
  {
    id: "ad_011",
    brandName: "PetPal Store",
    brandAvatar: "https://picsum.photos/seed/petpal/40/40",
    headline: "Your dog deserves the best",
    primaryText: "Premium organic dog food with real meat as the #1 ingredient. No fillers, no artificial additives.",
    mediaUrl: "https://picsum.photos/seed/petfood/640/640",
    mediaType: "image",
    cta: "Try risk-free",
    platform: "facebook",
    format: "image",
    category: "Pets",
    language: "English",
    views: 456000,
    estimatedSpend: 7800,
    runningDays: 65,
    firstSeenAt: "2026-01-10",
    angle: "Emotional",
    emotion: "Love",
    theme: "Warm",
    usp: "Organic",
    desire: "Care",
    tags: ["pet", "dog", "organic"],
  },
  {
    id: "ad_012",
    brandName: "TechFlow Pro",
    brandAvatar: "https://picsum.photos/seed/techflow/40/40",
    headline: "The last productivity app you'll ever need",
    primaryText: "Stop switching between 5 apps. TechFlow combines task management, notes, calendar, and team chat in one place.",
    mediaUrl: "https://picsum.photos/seed/techapp/640/640",
    mediaType: "video",
    duration: "00:45",
    cta: "Start free trial",
    platform: "facebook",
    format: "video",
    category: "Software & SaaS",
    language: "English",
    views: 320000,
    estimatedSpend: 5500,
    runningDays: 45,
    firstSeenAt: "2026-02-15",
    angle: "Problem / Solution",
    emotion: "Relief",
    theme: "Tech / Modern",
    usp: "All-in-one",
    desire: "Productivity",
    tags: ["saas", "productivity", "tech"],
  },
  {
    id: "ad_013",
    brandName: "NatureBrew Coffee",
    brandAvatar: "https://picsum.photos/seed/naturebrew/40/40",
    headline: "Coffee that actually tastes like coffee",
    primaryText: "Single-origin beans, roasted fresh weekly. Shipped to your door within 24 hours of roasting.",
    mediaUrl: "https://picsum.photos/seed/coffee/640/640",
    mediaType: "image",
    cta: "Shop now",
    platform: "instagram",
    format: "image",
    category: "Food & Beverage",
    language: "English",
    views: 178000,
    estimatedSpend: 3200,
    runningDays: 55,
    firstSeenAt: "2026-02-28",
    angle: "Social Proof",
    emotion: "Pleasure",
    theme: "Artisan",
    usp: "Fresh Roasted",
    desire: "Taste",
    tags: ["coffee", "food", "subscription"],
  },
  {
    id: "ad_014",
    brandName: "CozyHome Decor",
    brandAvatar: "https://picsum.photos/seed/cozyhome/40/40",
    headline: "Transform your living room in 5 minutes",
    primaryText: "Throw pillows, blankets, and decor that make any space feel like a luxury hotel. Free shipping over $50.",
    mediaUrl: "https://picsum.photos/seed/homedecor/640/640",
    mediaType: "image",
    cta: "Shop collection",
    platform: "instagram",
    format: "image",
    category: "Home & Garden",
    language: "English",
    views: 234000,
    estimatedSpend: 4100,
    runningDays: 38,
    firstSeenAt: "2026-03-05",
    angle: "Transformation",
    emotion: "Comfort",
    theme: "Lifestyle",
    usp: "Free Shipping",
    desire: "Comfort",
    tags: ["home", "decor", "lifestyle"],
  },
  {
    id: "ad_015",
    brandName: "SwiftLearn",
    brandAvatar: "https://picsum.photos/seed/swiftlearn/40/40",
    headline: "Learn a new language in 3 months",
    primaryText: "Our AI-powered method adapts to your learning speed. 15 minutes a day is all you need.",
    mediaUrl: "https://picsum.photos/seed/learning/640/640",
    mediaType: "video",
    duration: "00:20",
    cta: "Try free",
    platform: "facebook",
    format: "video",
    category: "Education",
    language: "English",
    views: 560000,
    estimatedSpend: 9800,
    runningDays: 72,
    firstSeenAt: "2026-01-20",
    angle: "Curiosity",
    emotion: "Excitement",
    theme: "Modern",
    usp: "AI-Powered",
    desire: "Achievement",
    tags: ["education", "language", "ai"],
  },
  {
    id: "ad_016",
    brandName: "LuxeTravel",
    brandAvatar: "https://picsum.photos/seed/luxetravel/40/40",
    headline: "5-star Bali villa for less than a hotel",
    primaryText: "Private pool, personal chef, ocean views. Book now and save up to 40%.",
    mediaUrl: "https://picsum.photos/seed/baliresort/640/800",
    mediaType: "image",
    cta: "Book now",
    platform: "instagram",
    format: "image",
    category: "Travel",
    language: "English",
    views: 1450000,
    estimatedSpend: 22000,
    runningDays: 110,
    firstSeenAt: "2025-11-01",
    angle: "Discount / Offer",
    emotion: "Aspiration",
    theme: "Luxury",
    usp: "Value for Money",
    desire: "Luxury",
    tags: ["travel", "bali", "luxury"],
  },
  {
    id: "ad_017",
    brandName: "BabyBliss",
    brandAvatar: "https://picsum.photos/seed/babybliss/40/40",
    headline: "The only baby monitor you'll ever need",
    primaryText: "HD video, two-way audio, sleep tracking. Peace of mind for new parents. 30-day free trial.",
    mediaUrl: "https://picsum.photos/seed/babymonitor/640/640",
    mediaType: "video",
    duration: "00:25",
    cta: "Start free trial",
    platform: "facebook",
    format: "video",
    category: "Baby & Kids",
    language: "English",
    views: 387000,
    estimatedSpend: 6500,
    runningDays: 80,
    firstSeenAt: "2026-01-05",
    angle: "Fear / Safety",
    emotion: "Peace",
    theme: "Warm",
    usp: "Free Trial",
    desire: "Safety",
    tags: ["baby", "parenting", "tech"],
  },
  {
    id: "ad_018",
    brandName: "GreenClean",
    brandAvatar: "https://picsum.photos/seed/greenclean/40/40",
    headline: "Clean your home without toxic chemicals",
    primaryText: "Plant-based formula. Safe for kids and pets. Works better than bleach.",
    mediaUrl: "https://picsum.photos/seed/cleaning/640/640",
    mediaType: "image",
    cta: "Get 20% off",
    platform: "facebook",
    format: "image",
    category: "Home & Garden",
    language: "English",
    views: 145000,
    estimatedSpend: 2800,
    runningDays: 35,
    firstSeenAt: "2026-03-10",
    angle: "Problem / Solution",
    emotion: "Safety",
    theme: "Eco / Natural",
    usp: "Non-Toxic",
    desire: "Safety",
    tags: ["cleaning", "eco", "home"],
  },
  {
    id: "ad_019",
    brandName: "AarrRnnii",
    brandAvatar: "https://picsum.photos/seed/aarrrnii/40/40",
    headline: "Would you swap your bag for my bag?",
    primaryText: "This bag has been with me for 3 years. Still looks brand new. Worth every penny.",
    mediaUrl: "https://picsum.photos/seed/handbag/640/640",
    mediaType: "video",
    duration: "00:32",
    cta: "Shop now",
    platform: "facebook",
    format: "video",
    category: "Fashion",
    language: "English",
    views: 5500000,
    estimatedSpend: 81800,
    runningDays: 203,
    firstSeenAt: "2025-07-22",
    angle: "Curiosity",
    emotion: "Desire",
    theme: "Lifestyle",
    usp: "Durability",
    desire: "Status",
    tags: ["fashion", "bags", "accessories"],
  },
  {
    id: "ad_020",
    brandName: "SleepWell",
    brandAvatar: "https://picsum.photos/seed/sleepwell/40/40",
    headline: "Finally sleep through the night",
    primaryText: "Doctor-formulated sleep supplement. Fall asleep faster, stay asleep longer. Drug-free.",
    mediaUrl: "https://picsum.photos/seed/sleep/640/640",
    mediaType: "image",
    cta: "Try tonight",
    platform: "facebook",
    format: "image",
    category: "Health & Wellness",
    language: "English",
    views: 670000,
    estimatedSpend: 11200,
    runningDays: 95,
    firstSeenAt: "2025-12-20",
    angle: "Problem / Solution",
    emotion: "Relief",
    theme: "Calm",
    usp: "Doctor Formulated",
    desire: "Health",
    tags: ["sleep", "supplement", "health"],
  },
]

export function formatViews(n?: number): string {
  if (!n) return "—"
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`
  if (n >= 1_000)     return `${(n / 1_000).toFixed(1)}K`
  return n.toString()
}

export function formatSpend(n?: number): string {
  if (!n) return "—"
  if (n >= 1_000) return `$${(n / 1_000).toFixed(1)}k`
  return `$${n}`
}

export function timeAgo(dateStr?: string): string {
  if (!dateStr) return ""
  const diff = Date.now() - new Date(dateStr).getTime()
  const days = Math.floor(diff / 86400000)
  if (days < 1)   return "today"
  if (days < 7)   return `${days}d ago`
  if (days < 30)  return `${Math.floor(days / 7)}w ago`
  if (days < 365) return `${Math.floor(days / 30)} months ago`
  return `${Math.floor(days / 365)}y ago`
}
